apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# - ../../base/jenkins
- https://github.com/jenkinsci/helm-charts/charts/jenkins?ref=HEAD
patches:
- patch-scc.yaml
# namespace: jenkins
# namePrefix: prod-
# nameSuffix: -test
# commonLabels:
#   someName: someValue
#   owner: alice
#   app: bingo
