apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jenkins

# commonLabels:
#   someName: someValue
#   owner: alice
#   app: bingo

resources:
- github.com/jenkinsci/helm-charts/charts/jenkins?ref=main
