apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jenkins
spec:
  template:
    spec:
      securityContext:
        runAsUser: 1000670000
        runAsGroup: 1000670000
        fsGroup: 1000670000