apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-artifactory
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: apps/artifactory-oss/base/charts/artifactory-oss
    helm:
      version: v2
      # values: |-
        # artifactory:
  destination:
    namespace: artifactory
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
