apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-jenkins
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: apps/jenkins/base/charts/jenkins
    helm:
      values: |-
        controller:
          installPlugins: []
          fsGroup: 1000650000
          runAsUser: 1000650000
          route:
            enabled: true
  destination:
    namespace: jenkins
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
