apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-sonarqube
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: apps/sonarqube/base/charts/sonarqube
    helm:
      version: v3
      values: |-
        OpenShift:
          enabled: true
          createSCC: false
        securityContext:
          fsGroup: 1000660000
        containerSecurityContext:
          runAsUser: 1000660000
        # initSysctl:
        #   securityContext:
        #     privileged: false
  destination:
    namespace: sonarqube
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
