apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-nexus
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: apps/sonatype-nexus/base/charts/sonatype-nexus
    helm:
      values: |-
        nexus:
          # securityContextEnabled: true
          # securityContext:
            # fsGroup: 1000650000
        # route:
          # enabled: true
  destination:
    namespace: nexus
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
